name = "Practice_Julia_Repositoria"
uuid = "d0be03a8-369d-4ca7-9270-779df52d5b0b"
authors = ["sandreza <andrenogueirasouza@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
